<center> <img src = https://raw.githubusercontent.com/AndreyRysistov/DatasetsForPandas/main/hh%20label.jpg alt="drawing" style="width:400px;">

# <center> Проект: Анализ вакансий из HeadHunter

In [49]:
import pandas as pd
import psycopg2
import requests
from bs4 import BeautifulSoup
import plotly.express as px

In [3]:
connection = psycopg2.connect(
    dbname=DBNAME,
    user=USER,
    host=HOST,
    password=PASSWORD,
    port=PORT
)

# Юнит 3. Предварительный анализ данных

1. Напишите запрос, который посчитает количество вакансий в нашей базе (вакансии находятся в таблице vacancies).

In [ ]:
# текст запроса
query_vac = f'''
    SELECT count(*)
    FROM vacancies
            '''
vac_df = pd.read_sql_query(query_vac, connection)
vac_df

C:\Users\Mephistophel\AppData\Local\Temp\ipykernel_8812\104183715.py:5: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  vac_df = pd.read_sql_query(query_vac, connection)

   count
0  49197

2. Напишите запрос, который посчитает количество работодателей (таблица employers).

In [ ]:
query_vac = f'''
    SELECT count(*)
    FROM employers
            '''
vac_df = pd.read_sql_query(query_vac, connection)

C:\Users\Mephistophel\AppData\Local\Temp\ipykernel_8812\2792477893.py:4: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  vac_df = pd.read_sql_query(query_vac, connection)

In [6]:
vac_df

   count
0  23501

3. Посчитате с помощью запроса количество регионов (таблица areas).

In [ ]:
query_vac = f'''
    SELECT count(*)
    FROM areas
            '''
vac_df = pd.read_sql_query(query_vac, connection)

C:\Users\Mephistophel\AppData\Local\Temp\ipykernel_8812\3185960307.py:4: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  vac_df = pd.read_sql_query(query_vac, connection)

In [8]:
vac_df

   count
0   1362

4. Посчитате с помощью запроса количество сфер деятельности в базе (таблица industries).

In [ ]:
query_vac = f'''
    SELECT count(*)
    FROM industries
            '''
vac_df = pd.read_sql_query(query_vac, connection)

C:\Users\Mephistophel\AppData\Local\Temp\ipykernel_8812\683599058.py:4: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  vac_df = pd.read_sql_query(query_vac, connection)

In [10]:
vac_df

   count
0    294

Согласно проанализированным данным, на каждого работодателя приходится всреднем по 2 вакансии, а на каждый из 1 362 регионов всреднем приходится по 17 работодетелей. При этом в рамках каждой из сфер деятельности размещено всреднем 167 вакансий.

***

# Юнит 4. Детальный анализ вакансий

1. Напишите запрос, который позволит узнать, сколько (cnt) вакансий в каждом регионе (area).
Отсортируйте по количеству вакансий в порядке убывания.

In [ ]:
query_vac = f'''
    SELECT 
        a.name, 
        count(v.id) as cnt
    FROM  
        employers e, areas a, vacancies v
    WHERE 
        v.area_id = a.id and v.employer_id = e.id
    GROUP BY 
        a.id
    ORDER BY 
        cnt desc
    '''
vac_df = pd.read_sql_query(query_vac, connection)

C:\Users\Mephistophel\AppData\Local\Temp\ipykernel_8812\2518048130.py:8: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  vac_df = pd.read_sql_query(query_vac, connection)

In [12]:
vac_df

                         name   cnt
0                      Москва  5333
1             Санкт-Петербург  2851
2                       Минск  2112
3                 Новосибирск  2006
4                      Алматы  1892
..                        ...   ...
764                    Кизляр     1
765                    Джизак     1
766                    Эртиль     1
767                  Арсеньев     1
768  Тура (Красноярский край)     1

[769 rows x 2 columns]

2. Напишите запрос, чтобы определить у какого количества вакансий заполнено хотя бы одно из двух полей с зарплатой.

In [ ]:
query_vac = f'''
        SELECT count(*) 
        FROM  vacancies 
        WHERE salary_from is not null or salary_to is not null
        '''
vac_df = pd.read_sql_query(query_vac, connection)

C:\Users\Mephistophel\AppData\Local\Temp\ipykernel_8812\1358740907.py:4: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  vac_df = pd.read_sql_query(query_vac, connection)

In [14]:
vac_df

   count
0  24073

3. Найдите средние значения для нижней и верхней границы зарплатной вилки. Округлите значения до целого.

In [ ]:
query_vac = f'''
        SELECT 
           round(avg(salary_from)) as salary_mean_min, 
           round(avg(salary_to)) as salary_mean_max 
        FROM  vacancies
        '''
vac_df = pd.read_sql_query(query_vac, connection)

C:\Users\Mephistophel\AppData\Local\Temp\ipykernel_8812\2767690447.py:4: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  vac_df = pd.read_sql_query(query_vac, connection)

In [16]:
vac_df

   salary_mean_min  salary_mean_max
0          71065.0         110537.0

4. Напишите запрос, который выведет количество вакансий для каждого сочетания типа рабочего графика (schedule) и типа трудоустройства (employment), используемого в вакансиях. Результат отсортируйте по убыванию количества.

In [ ]:
query_vac = f'''
SELECT 
   v.schedule, 
   v.employment, 
   count(*) as cnt 
FROM  public.vacancies v 
GROUP BY v.schedule, v.employment 
order by cnt desc
        '''
vac_df = pd.read_sql_query(query_vac, connection)

C:\Users\Mephistophel\AppData\Local\Temp\ipykernel_8812\2490742774.py:4: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  vac_df = pd.read_sql_query(query_vac, connection)

In [18]:
vac_df

            schedule           employment    cnt
0        Полный день     Полная занятость  35367
1   Удаленная работа     Полная занятость   7802
2      Гибкий график     Полная занятость   1593
3   Удаленная работа  Частичная занятость   1312
4     Сменный график     Полная занятость    940
5        Полный день           Стажировка    569
6     Вахтовый метод     Полная занятость    367
7        Полный день  Частичная занятость    347
8      Гибкий график  Частичная занятость    312
9        Полный день     Проектная работа    141
10  Удаленная работа     Проектная работа    133
11     Гибкий график           Стажировка    116
12    Сменный график  Частичная занятость    101
13  Удаленная работа           Стажировка     64
14     Гибкий график     Проектная работа     18
15    Сменный график           Стажировка     12
16    Вахтовый метод     Проектная работа      2
17    Сменный график     Проектная работа      1

5. Напишите запрос, выводящий значения поля Требуемый опыт работы (experience) в порядке возрастания количества вакансий, в которых указан данный вариант опыта.

In [ ]:
query_vac = f'''
     SELECT 
        v.experience as "Требуемый опыт работы", 
        count(*) as cnt 
     FROM  VACANCIES v 
     GROUP BY v.experience 
     ORDER BY cnt
        '''
vac_df = pd.read_sql_query(query_vac, connection)

C:\Users\Mephistophel\AppData\Local\Temp\ipykernel_8812\2360917534.py:4: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  vac_df = pd.read_sql_query(query_vac, connection)

In [20]:
vac_df

  Требуемый опыт работы    cnt
0           Более 6 лет   1337
1             Нет опыта   7197
2         От 3 до 6 лет  14511
3    От 1 года до 3 лет  26152

***

**Выводы по юниту:**
 - больше всего вакансий размещено в Москве. На втором месте находится Санкт-Петербург, но там вакансий сразу в 2 раза меньше, чем в столице;
 - при 49 тыс вакансий лишь в 24-х тыс из них заполнено хотя бы одно поле с зарплатой;
 - средняя ставка колеблется в диапазоне от 71 тыс руб до 110 тыс руб;
 - подавляющее число вакансий подразумевают полную занятость;
 - больше половины вакансий рассматривают соискателей с опытой работы от 1 до 3 лет.

# Юнит 5. Анализ работодателей

1. Напишите запрос, который позволит узнать, какие работодатели находятся на первом и пятом месте по количеству вакансий.

In [ ]:
query_vac = f'''
    WITH RankedEmployers as (
    SELECT 
        e.name,
        count(v.id) AS vacancy_count,
        -- Присваиваем номер каждому работодателю по убыванию вакансий
        row_number() over (order by count(v.id) desc) as rn
    FROM 
        employers e
    JOIN 
        vacancies v on e.id = v.employer_id
    GROUP BY
        e.id, e.name
)
SELECT name, vacancy_count
FROM RankedEmployers
WHERE rn = 1 or rn = 5;
        '''
vac_df = pd.read_sql_query(query_vac, connection)

C:\Users\Mephistophel\AppData\Local\Temp\ipykernel_8812\3995118890.py:19: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  vac_df = pd.read_sql_query(query_vac, connection)

In [22]:
vac_df

            name  vacancy_count
0         Яндекс           1933
1  Газпром нефть            331

2. Напишите запрос, который для каждого региона выведет количество работодателей и вакансий в нём.
Среди регионов, в которых нет вакансий, найдите тот, в котором наибольшее количество работодателей.

In [23]:
query_vac = f'''
    SELECT       
        a.name AS "Регион",
        COUNT(e.name) AS "Кол-во работодателей",
        COUNT(v.name) AS "Кол-во вакансий"
    FROM public.areas a
        LEFT JOIN public.employers e ON a.id = e.area
        LEFT JOIN public.vacancies v ON a.id = v.area_id
    WHERE v.area_id IS NULL
    GROUP BY 1
    ORDER BY 3, 2 DESC
    LIMIT 5
        '''
vac_df = pd.read_sql_query(query_vac, connection)

C:\Users\Mephistophel\AppData\Local\Temp\ipykernel_8812\177187971.py:14: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  vac_df = pd.read_sql_query(query_vac, connection)

In [24]:
vac_df.head()

               Регион  Кол-во работодателей  Кол-во вакансий
0              Россия                   410                0
1           Казахстан                   207                0
2  Московская область                    75                0
3  Краснодарский край                    19                0
4            Беларусь                    18                0

3. Для каждого работодателя посчитайте количество регионов, в которых он публикует свои вакансии. Отсортируйте результат по убыванию количества.

In [ ]:
query_vac = f'''
SELECT 
    name "Компания",
    COUNT(DISTINCT e.area) AS "Кол-во регионов"
FROM 
    employers e
GROUP BY
    e.name
ORDER BY 
    "Кол-во регионов" DESC;

        '''
vac_df = pd.read_sql_query(query_vac, connection)

C:\Users\Mephistophel\AppData\Local\Temp\ipykernel_8812\1891194057.py:13: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  vac_df = pd.read_sql_query(query_vac, connection)

In [26]:
vac_df

               Компания  Кол-во регионов
0               Бастион                5
1              Прогресс                5
2      Новые Технологии                5
3                Модуль                5
4                   ИТС                4
...                 ...              ...
23170         Afrosiyob                1
23171    Afterlogic Rus                1
23172    AGAMA IT Group                1
23173          AGASTONE                1
23174      Agenda Media                1

[23175 rows x 2 columns]

4. Напишите запрос для подсчёта количества работодателей, у которых не указана сфера деятельности.

In [ ]:
query_vac = f'''
    SELECT 
        COUNT(distinct e.id) AS "Кол-во компаний без сферы деятельности"
    FROM 
        EMPLOYERS e
    left outer join 
        EMPLOYERS_INDUSTRIES i on i.employer_id = e.id 
    WHERE 
        i.industry_id is null
'''
vac_df = pd.read_sql_query(query_vac, connection)

C:\Users\Mephistophel\AppData\Local\Temp\ipykernel_8812\2010838045.py:7: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  vac_df = pd.read_sql_query(query_vac, connection)

In [28]:
vac_df

   Кол-во компаний без сферы деятельн
0                                8419

5. Напишите запрос, чтобы узнать название компании, находящейся на третьем месте в алфавитном списке (по названию) компаний, у которых указано четыре сферы деятельности.

In [ ]:
query_vac = f'''
    SELECT 
        e.name "Название компании"
    FROM 
        EMPLOYERS e
    LEFT JOIN 
        EMPLOYERS_INDUSTRIES i on i.employer_id = e.id 
    GROUP BY 
        e.name having count(i.industry_id) = 4 order by 1
'''
vac_df = pd.read_sql_query(query_vac, connection)

C:\Users\Mephistophel\AppData\Local\Temp\ipykernel_8812\1017435790.py:7: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  vac_df = pd.read_sql_query(query_vac, connection)

In [30]:
vac_df

     Название компании
0         101 Интернет
1             21vek.by
2                 2ГИС
3                   2К
4          4 пикселя +
...                ...
1131             ЮРИОН
1132   ЮТИП Технологии
1133            ЯКласс
1134             ЯрНео
1135     Яшин&Партнёры

[1136 rows x 1 columns]

6. С помощью запроса выясните, у какого количества работодателей в качестве сферы деятельности указана Разработка программного обеспечения.

In [ ]:
query_vac = f'''
SELECT 
  count(ei.employer_id) "Количество компаний"
FROM 
  EMPLOYERS_INDUSTRIES ei
LEFT JOIN 
  INDUSTRIES i on i.id = ei.industry_id 
WHERE 
  i.name = 'Разработка программного обеспечения'
'''
vac_df = pd.read_sql_query(query_vac, connection)

C:\Users\Mephistophel\AppData\Local\Temp\ipykernel_8812\2932379450.py:7: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  vac_df = pd.read_sql_query(query_vac, connection)

In [32]:
vac_df

   Количество компаний
0                 3553

7. Для компании «Яндекс» выведите список регионов-миллионников, в которых представлены вакансии компании, вместе с количеством вакансий в этих регионах. Также добавьте строку Total с общим количеством вакансий компании. Результат отсортируйте по возрастанию количества.

Список городов-милионников надо взять [отсюда](https://ru.wikipedia.org/wiki/%D0%93%D0%BE%D1%80%D0%BE%D0%B4%D0%B0-%D0%BC%D0%B8%D0%BB%D0%BB%D0%B8%D0%BE%D0%BD%D0%B5%D1%80%D1%8B_%D0%A0%D0%BE%D1%81%D1%81%D0%B8%D0%B8). 

Если возникнут трудности с этим задание посмотрите материалы модуля  PYTHON-17. Как получать данные из веб-источников и API.

In [ ]:
# код для получения списка городов-милионников
url = 'https://ru.wikipedia.org/wiki/%D0%93%D0%BE%D1%80%D0%BE%D0%B4%D0%B0-%D0%BC%D0%B8%D0%BB%D0%BB%D0%B8%D0%BE%D0%BD%D0%B5%D1%80%D1%8B_%D0%A0%D0%BE%D1%81%D1%81%D0%B8%D0%B8'
response = requests.get(url, headers={'User-Agent': '...'}) #поиск по странице не осуществлялся без указания 'User-Agent':
soup = BeautifulSoup(response.text, 'html.parser')
#tables = soup.find_all('table')
#print(tables)
# Поиск таблицы по классу standard sortable (пришлось сначала найти и напечатать все таблицы на странице, 
# чтобы выяснить класс CSS)
table = soup.find('table', {'class': 'standard sortable'})
print(table)
cities = []

# Перебираем строки таблицы, пропуская заголовок
for row in table.find_all('tr')[1:]:
    cells = row.find_all('td')
    if len(cells) > 1:
        # Название города обычно находится во второй колонке (индекс 1)
        city = cells[1].text.strip()
        # Убираем ссылки на сноски вроде [a], [1]
        city = city.split('[')[0] 
        cities.append(city)

print(cities)

<table about="#mwt5" class="standard sortable" data-mw='{"parts":[{"template":{"target":{"wt":"Автонумерация\n ","href":"./Шаблон:Автонумерация"},"params":{"Столбцов":{"wt":"6"},"Оформление":{"wt":"standard sortable"},"Заголовок2":{"wt":"Город"},"Заголовок3":{"wt":"Население, &lt;br&gt; тыс. чел.&lt;br&gt;&lt;small&gt;  (на 1 января 2025)&lt;ref name=\"jan01\"&gt;{{Население/2025AA}}&lt;/ref&gt;"},"Заголовок4":{"wt":"Население, &lt;br&gt; тыс. чел.&lt;br&gt;&lt;small&gt; ([[Всероссийская перепись населения (2020—2021)|перепись-2021]])&lt;ref name=\"ofperep21\"&gt;{{Население/2021RU}}&lt;/ref&gt;&lt;/small&gt;"},"Заголовок5":{"wt":"Прирост&lt;br&gt; относительно&lt;br&gt;  переписи-2010"},"Заголовок6":{"wt":"Население, &lt;br&gt; тыс. чел.&lt;br&gt;&lt;small&gt;([[Всероссийская перепись населения (2010)|перепись-2010]])&lt;ref name=\"GKS_100\"&gt;{{Cite web |url=http://www.gks.ru/free_doc/new_site/perepis2010/croc/Documents/Vol1/pub-01-05.xlsx |title=Росстат. Федеральная служба Государственной статистики. Города с численностью населения 100 тысяч человек и более |access-date=2012-06-04 |archive-date=2013-07-02 |archive-url=https://web.archive.org/web/20130702213008/http://www.gks.ru/free_doc/new_site/perepis2010/croc/Documents/Vol1/pub-01-05.xlsx |url-status=live }}&lt;/ref&gt;&lt;/small&gt;"},"Сортировка3":{"wt":"число"},"Выравнивание3":{"wt":"right"},"Сортировка4":{"wt":"число"},"Выравнивание4":{"wt":"right"},"Сортировка5":{"wt":"число"},"Выравнивание5":{"wt":"right"},"Сортировка6":{"wt":"число"},"Выравнивание6":{"wt":"right"},"1":{"wt":" "},"2":{"wt":"\t[[Москва]]"},"3":{"wt":"13 274"},"4":{"wt":"13 010\t"},"5":{"wt":" \t13,1 %\t"},"6":{"wt":" \t11 504\n"},"7":{"wt":" "},"8":{"wt":"\t[[Санкт-Петербург]]"},"9":{"wt":"5 653"},"10":{"wt":" \t5 602\t"},"11":{"wt":" \t14,8 %\t"},"12":{"wt":" \t4 880\n"},"13":{"wt":" "},"14":{"wt":"\t[[Новосибирск]]"},"15":{"wt":"1 637"},"16":{"wt":"1 634\t"},"17":{"wt":" \t10,9 %\t"},"18":{"wt":" \t1 474\n"},"19":{"wt":" "},"20":{"wt":"\t[[Екатеринбург]]"},"21":{"wt":"1 548"},"22":{"wt":" \t1 544\t"},"23":{"wt":" \t14,4 %\t"},"24":{"wt":" \t1 350\n"},"25":{"wt":" "},"26":{"wt":"\t[[Казань]]"},"27":{"wt":"1 330"},"28":{"wt":"\t1 309\t"},"29":{"wt":" \t14,4 %\t"},"30":{"wt":" \t1 144\n"},"31":{"wt":" "},"32":{"wt":"\t[[Красноярск]]"},"33":{"wt":"1 212"},"34":{"wt":"1 188\t"},"35":{"wt":" \t21,6 %\t"},"36":{"wt":" \t977\n"},"37":{"wt":" "},"38":{"wt":"\t[[Нижний Новгород]]"},"39":{"wt":" 1 198"},"40":{"wt":"1 226\t"},"41":{"wt":" \t{{~|0,2}}−2,0 %\t"},"42":{"wt":" \t1 251\n"},"43":{"wt":" "},"44":{"wt":"\t[[Челябинск]]"},"45":{"wt":"1 177"},"46":{"wt":"1 190\t"},"47":{"wt":" \t5,3 %\t"},"48":{"wt":" \t1 130\n"},"49":{"wt":" "},"50":{"wt":"\t[[Уфа]]"},"51":{"wt":"1 166"},"52":{"wt":"1 145"},"53":{"wt":" \t7,8 %\t"},"54":{"wt":" \t1 062\n"},"55":{"wt":" "},"56":{"wt":"\t[[Краснодар]]"},"57":{"wt":"1 155"},"58":{"wt":" \t1 099\t"},"59":{"wt":" \t43,8 %\t"},"60":{"wt":" \t764\n"},"61":{"wt":" "},"62":{"wt":"\t[[Самара]]"},"63":{"wt":"1 154"},"64":{"wt":"1 173\t"},"65":{"wt":" \t0,3 %\t"},"66":{"wt":" \t1 169\n"},"67":{"wt":" "},"68":{"wt":"\t[[Ростов-на-Дону]]"},"69":{"wt":"1 143"},"70":{"wt":" \t1 142\t"},"71":{"wt":" \t4,9 %\t"},"72":{"wt":" \t1 089\n"},"73":{"wt":" "},"74":{"wt":"\t[[Омск]]"},"75":{"wt":"1 101"},"76":{"wt":"1 126\t"},"77":{"wt":" \t{{~|0,1}}−3,4 %\t"},"78":{"wt":" \t1 166\n"},"79":{"wt":" "},"80":{"wt":"\t[[Воронеж]]"},"81":{"wt":"1 042"},"82":{"wt":"1 058\t"},"83":{"wt":" \t18,9 %\t"},"84":{"wt":" \t890\n"},"85":{"wt":" "},"86":{"wt":"\t[[Пермь]]"},"87":{"wt":"1 028"},"88":{"wt":"1 034\t"},"89":{"wt":" \t4,3 %\t"},"90":{"wt":" \t991\n"},"91":{"wt":" "},"92":{"wt":"\t[[Волгоград]]"},"93":{"wt":"1 012"},"94":{"wt":" \t1 028\t"},"95":{"wt":" \t0,7 %\t"},"96":{"wt":" \t1 021\n"}},"i":0}}]}' id="mwGA" typeof="mw:Transclusion"><tbody><tr><th scope="col">№</th><th scope="col">Город</th><th data-sort-type="number" scope="col">Население, <br/> тыс. чел.<br/><small>  (на 1 января 2025)<sup about="#mwt7" class="mw-ref reference" data-mw='{"name":"ref","attrs":{"name":"jan01"},"body":{"id":"mw-reference-text-cite_note-jan01-2"}}' id="cite_ref-jan01_2-0" rel="dc:references" typeof="mw:Extension/ref"><a href="#cite_note-jan01-2" id="mwGQ"><span class="mw-reflink-text" id="mwGg"><span class="cite-bracket" id="mwGw">[</span>2<span class="cite-bracket" id="mwHA">]</span></span></a></sup></small></th><th data-sort-type="number" scope="col">Население, <br/> тыс. чел.<br/><small> (<a href="//ru.wikipedia.org/wiki/Всероссийская_перепись_населения_(2020—2021)" rel="mw:WikiLink" title="Всероссийская перепись населения (2020—2021)">перепись-2021</a>)<sup about="#mwt9" class="mw-ref reference" data-mw='{"name":"ref","attrs":{"name":"ofperep21"},"body":{"id":"mw-reference-text-cite_note-ofperep21-3"}}' id="cite_ref-ofperep21_3-0" rel="dc:references" typeof="mw:Extension/ref"><a href="#cite_note-ofperep21-3" id="mwHQ"><span class="mw-reflink-text" id="mwHg"><span class="cite-bracket" id="mwHw">[</span>3<span class="cite-bracket" id="mwIA">]</span></span></a></sup></small></th><th data-sort-type="number" scope="col">Прирост<br/> относительно<br/>  переписи-2010</th><th data-sort-type="number" scope="col">Население, <br/> тыс. чел.<br/><small>(<a href="//ru.wikipedia.org/wiki/Всероссийская_перепись_населения_(2010)" rel="mw:WikiLink" title="Всероссийская перепись населения (2010)">перепись-2010</a>)<sup about="#mwt11" class="mw-ref reference" data-mw='{"name":"ref","attrs":{"name":"GKS_100"},"body":{"id":"mw-reference-text-cite_note-GKS_100-4"}}' id="cite_ref-GKS_100_4-0" rel="dc:references" typeof="mw:Extension/ref"><a href="#cite_note-GKS_100-4" id="mwIQ"><span class="mw-reflink-text" id="mwIg"><span class="cite-bracket" id="mwIw">[</span>4<span class="cite-bracket" id="mwJA">]</span></span></a></sup></small></th></tr><tr><td style="text-align:center">1</td><td><a href="//ru.wikipedia.org/wiki/Москва" rel="mw:WikiLink" title="Москва">Москва</a></td><td data-sort-value="13274" style="text-align:right">13 274</td><td data-sort-value="13010" style="text-align:right">13 010</td><td data-sort-value="13.1" style="text-align:right">13,1<span typeof="mw:DisplaySpace"> </span>%</td><td data-sort-value="11504" style="text-align:right">11 504</td></tr><tr><td style="text-align:center">2</td><td><a href="//ru.wikipedia.org/wiki/Санкт-Петербург" rel="mw:WikiLink" title="Санкт-Петербург">Санкт-Петербург</a></td><td data-sort-value="5653" style="text-align:right">5 653</td><td data-sort-value="5602" style="text-align:right">5 602</td><td data-sort-value="14.8" style="text-align:right">14,8<span typeof="mw:DisplaySpace"> </span>%</td><td data-sort-value="4880" style="text-align:right">4 880</td></tr><tr><td style="text-align:center">3</td><td><a href="//ru.wikipedia.org/wiki/Новосибирск" rel="mw:WikiLink" title="Новосибирск">Новосибирск</a></td><td data-sort-value="1637" style="text-align:right">1 637</td><td data-sort-value="1634" style="text-align:right">1 634</td><td data-sort-value="10.9" style="text-align:right">10,9<span typeof="mw:DisplaySpace"> </span>%</td><td data-sort-value="1474" style="text-align:right">1 474</td></tr><tr><td style="text-align:center">4</td><td><a href="//ru.wikipedia.org/wiki/Екатеринбург" rel="mw:WikiLink" title="Екатеринбург">Екатеринбург</a></td><td data-sort-value="1548" style="text-align:right">1 548</td><td data-sort-value="1544" style="text-align:right">1 544</td><td data-sort-value="14.4" style="text-align:right">14,4<span typeof="mw:DisplaySpace"> </span>%</td><td data-sort-value="1350" style="text-align:right">1 350</td></tr><tr><td style="text-align:center">5</td><td><a href="//ru.wikipedia.org/wiki/Казань" rel="mw:WikiLink" title="Казань">Казань</a></td><td data-sort-value="1330" style="text-align:right">1 330</td><td data-sort-value="1309" style="text-align:right">1 309</td><td data-sort-value="14.4" style="text-align:right">14,4<span typeof="mw:DisplaySpace"> </span>%</td><td data-sort-value="1144" style="text-align:right">1 144</td></tr><tr><td style="text-align:center">6</td><td><a href="//ru.wikipedia.org/wiki/Красноярск" rel="mw:WikiLink" title="Красноярск">Красноярск</a></td><td data-sort-value="1212" style="text-align:right">1 212</td><td data-sort-value="1188" style="text-align:right">1 188</td><td data-sort-value="21.6" style="text-align:right">21,6<span typeof="mw:DisplaySpace"> </span>%</td><td data-sort-value="977" style="text-align:right">977</td></tr><tr><td style="text-align:center">7</td><td><a href="//ru.wikipedia.org/wiki/Нижний_Новгород" rel="mw:WikiLink" title="Нижний Новгород">Нижний Новгород</a></td><td data-sort-value="1198" style="text-align:right">1 198</td><td data-sort-value="1226" style="text-align:right">1 226</td><td data-sort-value="0.2" style="text-align:right"><span class="noprint" style="display: none;">0,2</span>−2,0<span typeof="mw:DisplaySpace"> </span>%</td><td data-sort-value="1251" style="text-align:right">1 251</td></tr><tr><td style="text-align:center">8</td><td><a href="//ru.wikipedia.org/wiki/Челябинск" rel="mw:WikiLink" title="Челябинск">Челябинск</a></td><td data-sort-value="1177" style="text-align:right">1 177</td><td data-sort-value="1190" style="text-align:right">1 190</td><td data-sort-value="5.3" style="text-align:right">5,3<span typeof="mw:DisplaySpace"> </span>%</td><td data-sort-value="1130" style="text-align:right">1 130</td></tr><tr><td style="text-align:center">9</td><td><a href="//ru.wikipedia.org/wiki/Уфа" rel="mw:WikiLink" title="Уфа">Уфа</a></td><td data-sort-value="1166" style="text-align:right">1 166</td><td data-sort-value="1145" style="text-align:right">1 145</td><td data-sort-value="7.8" style="text-align:right">7,8<span typeof="mw:DisplaySpace"> </span>%</td><td data-sort-value="1062" style="text-align:right">1 062</td></tr><tr><td style="text-align:center">10</td><td><a href="//ru.wikipedia.org/wiki/Краснодар" rel="mw:WikiLink" title="Краснодар">Краснодар</a></td><td data-sort-value="1155" style="text-align:right">1 155</td><td data-sort-value="1099" style="text-align:right">1 099</td><td data-sort-value="43.8" style="text-align:right">43,8<span typeof="mw:DisplaySpace"> </span>%</td><td data-sort-value="764" style="text-align:right">764</td></tr><tr><td style="text-align:center">11</td><td><a href="//ru.wikipedia.org/wiki/Самара" rel="mw:WikiLink" title="Самара">Самара</a></td><td data-sort-value="1154" style="text-align:right">1 154</td><td data-sort-value="1173" style="text-align:right">1 173</td><td data-sort-value="0.3" style="text-align:right">0,3<span typeof="mw:DisplaySpace"> </span>%</td><td data-sort-value="1169" style="text-align:right">1 169</td></tr><tr><td style="text-align:center">12</td><td><a href="//ru.wikipedia.org/wiki/Ростов-на-Дону" rel="mw:WikiLink" title="Ростов-на-Дону">Ростов-на-Дону</a></td><td data-sort-value="1143" style="text-align:right">1 143</td><td data-sort-value="1142" style="text-align:right">1 142</td><td data-sort-value="4.9" style="text-align:right">4,9<span typeof="mw:DisplaySpace"> </span>%</td><td data-sort-value="1089" style="text-align:right">1 089</td></tr><tr><td style="text-align:center">13</td><td><a href="//ru.wikipedia.org/wiki/Омск" rel="mw:WikiLink" title="Омск">Омск</a></td><td data-sort-value="1101" style="text-align:right">1 101</td><td data-sort-value="1126" style="text-align:right">1 126</td><td data-sort-value="0.1" style="text-align:right"><span class="noprint" style="display: none;">0,1</span>−3,4<span typeof="mw:DisplaySpace"> </span>%</td><td data-sort-value="1166" style="text-align:right">1 166</td></tr><tr><td style="text-align:center">14</td><td><a href="//ru.wikipedia.org/wiki/Воронеж" rel="mw:WikiLink" title="Воронеж">Воронеж</a></td><td data-sort-value="1042" style="text-align:right">1 042</td><td data-sort-value="1058" style="text-align:right">1 058</td><td data-sort-value="18.9" style="text-align:right">18,9<span typeof="mw:DisplaySpace"> </span>%</td><td data-sort-value="890" style="text-align:right">890</td></tr><tr><td style="text-align:center">15</td><td><a href="//ru.wikipedia.org/wiki/Пермь" rel="mw:WikiLink" title="Пермь">Пермь</a></td><td data-sort-value="1028" style="text-align:right">1 028</td><td data-sort-value="1034" style="text-align:right">1 034</td><td data-sort-value="4.3" style="text-align:right">4,3<span typeof="mw:DisplaySpace"> </span>%</td><td data-sort-value="991" style="text-align:right">991</td></tr><tr><td style="text-align:center">16</td><td><a href="//ru.wikipedia.org/wiki/Волгоград" rel="mw:WikiLink" title="Волгоград">Волгоград</a></td><td data-sort-value="1012" style="text-align:right">1 012</td><td data-sort-value="1028" style="text-align:right">1 028</td><td data-sort-value="0.7" style="text-align:right">0,7<span typeof="mw:DisplaySpace"> </span>%</td><td data-sort-value="1021" style="text-align:right">1 021</td></tr></tbody></table>
['Москва', 'Санкт-Петербург', 'Новосибирск', 'Екатеринбург', 'Казань', 'Красноярск', 'Нижний Новгород', 'Челябинск', 'Уфа', 'Краснодар', 'Самара', 'Ростов-на-Дону', 'Омск', 'Воронеж', 'Пермь', 'Волгоград']

In [ ]:
query_vac = f'''
(
    SELECT 
        a.name, 
        count(distinct v.id) as cnt
    FROM 
        vacancies v
    LEFT JOIN 
        employers e on e.id = v.employer_id
    LEFT JOIN 
        areas a on a.id = v.area_id
    WHERE 
        a.name in {repr(tuple(map(str, cities)))} and e.name = 'Яндекс'
    GROUP BY 
        a.name order by 2
 )
 union all
 (
     SELECT 
        'Total' as Total, 
        sum(t.cnt) 
        FROM (
            SELECT count(distinct v.id) as cnt
            FROM 
                vacancies v
            LEFT JOIN
                employers e on e.id = v.employer_id
            LEFT JOIN
                areas a on a.id = v.area_id
            WHERE
                a.name in {repr(tuple(map(str, cities)))} and e.name = 'Яндекс'
            GROUP BY
                a.name
     ) as t
     
)
'''
vac_df = pd.read_sql_query(query_vac, connection)

C:\Users\Mephistophel\AppData\Local\Temp\ipykernel_8812\3952289837.py:23: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  vac_df = pd.read_sql_query(query_vac, connection)

In [35]:
vac_df

               name    cnt
0              Омск   21.0
1         Челябинск   22.0
2        Красноярск   23.0
3         Волгоград   24.0
4             Пермь   25.0
5            Казань   25.0
6    Ростов-на-Дону   25.0
7               Уфа   26.0
8            Самара   26.0
9         Краснодар   30.0
10          Воронеж   32.0
11      Новосибирск   35.0
12  Нижний Новгород   36.0
13     Екатеринбург   39.0
14  Санкт-Петербург   42.0
15           Москва   54.0
16            Total  485.0

***

**Выводы по анализу работодателей:**
 - работодателем с наибольшим числом размещенных вакансий является Яндекс;
 - работодатели, наиболее широко представленные по регионам: Бастион, Прогресс, Новые Технологии, Модуль - их вакансии представлены в 5-ти регионах одновременно;
 - при этом 1135 работодателей представлены в 4-х регионах;
 - у компании Яндекс размещено 485 вакансий, больше всего в Москве - 54 вакансии.

# Юнит 6. Предметный анализ

1. Сколько вакансий имеет отношение к данным?

Считаем, что вакансия имеет отношение к данным, если в её названии содержатся слова 'data' или 'данн'.

*Подсказка: Обратите внимание, что названия вакансий могут быть написаны в любом регистре.*

In [ ]:
query_vac = f'''
    SELECT 
        count(name) as cnt_vacan 
    FROM  vacancies      
    WHERE 
        name ILIKE'%data%' 
        or name ILIKE'%данн%'
'''
vac_df = pd.read_sql_query(query_vac, connection)

C:\Users\Mephistophel\AppData\Local\Temp\ipykernel_8812\2375287305.py:10: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  vac_df = pd.read_sql_query(query_vac, connection)

In [37]:
vac_df

   cnt_vacan
0       1771

2. Сколько есть подходящих вакансий для начинающего дата-сайентиста? 
Будем считать вакансиями для дата-сайентистов такие, в названии которых есть хотя бы одно из следующих сочетаний:
* 'data scientist'
* 'data science'
* 'исследователь данных'
* 'ML' (здесь не нужно брать вакансии по HTML)
* 'machine learning'
* 'машинн%обучен%'

** В следующих заданиях мы продолжим работать с вакансиями по этому условию.*

Считаем вакансиями для специалистов уровня Junior следующие:
* в названии есть слово 'junior' *или*
* требуемый опыт — Нет опыта *или*
* тип трудоустройства — Стажировка.

In [ ]:
query_vac = f'''
    SELECT   
        count(name) AS cnt_DataScience_Junior
    FROM 
        vacancies 
    WHERE 
        (name ILIKE '%data scientist%'
        or name ILIKE  '%data science%'
        or name ILIKE  '%исследователь данных%'
        or (name LIKE  '%ML%' and name NOT ILIKE '%HTML%')
        or name ILIKE  '%machine learning%'
        or name ILIKE  '%машинн%обучен%')
        
        AND (name ILIKE '%junior%'
        OR experience ILIKE '%Нет опыта%'
        OR employment ILIKE '%Стажировка%')
'''
vac_df = pd.read_sql_query(query_vac, connection)

C:\Users\Mephistophel\AppData\Local\Temp\ipykernel_8812\3525243405.py:18: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  vac_df = pd.read_sql_query(query_vac, connection)

In [39]:
vac_df

   cnt_datascience_junior
0                      51

3. Сколько есть вакансий для DS, в которых в качестве ключевого навыка указан SQL или postgres?

** Критерии для отнесения вакансии к DS указаны в предыдущем задании.*

In [ ]:
query_vac = f'''
    SELECT
        count(name) as cnt_DS_SQL_postgres
    FROM  vacancies  
    WHERE 
        (name ILIKE '%data scientist%'
        or name ILIKE  '%data science%'
        or name ILIKE  '%исследователь данных%'
        or (name LIKE  '%ML%' and name NOT ILIKE '%HTML%')
        or name ILIKE  '%machine learning%'
        or name ILIKE  '%машинн%обучен%')
        
        AND (key_skills ILIKE '%SQL%'
        OR key_skills ILIKE '%postgres%')
'''
vac_df = pd.read_sql_query(query_vac, connection)

C:\Users\Mephistophel\AppData\Local\Temp\ipykernel_8812\1807500466.py:17: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  vac_df = pd.read_sql_query(query_vac, connection)

In [41]:
vac_df

   cnt_ds_sql_postgres
0                  201

4. Проверьте, насколько популярен Python в требованиях работодателей к DS.Для этого вычислите количество вакансий, в которых в качестве ключевого навыка указан Python.

** Это можно сделать помощью запроса, аналогичного предыдущему.*

In [ ]:
query_vac = f'''
    SELECT
        count(name) AS cnt_DataScience_Python
    FROM
        vacancies   
    WHERE 
        (name ILIKE '%data scientist%'
        or name ILIKE  '%data science%'
        or name ILIKE  '%исследователь данных%'
        or (name LIKE  '%ML%' and name NOT ILIKE '%HTML%')
        or name ILIKE  '%machine learning%'
        or name ILIKE  '%машинн%обучен%')
        
        AND (key_skills ILIKE '%Python%')
'''
vac_df = pd.read_sql_query(query_vac, connection)

C:\Users\Mephistophel\AppData\Local\Temp\ipykernel_8812\887753781.py:16: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  vac_df = pd.read_sql_query(query_vac, connection)

In [43]:
vac_df

   cnt_datascience_python
0                     351

5. Сколько ключевых навыков в среднем указывают в вакансиях для DS?
Ответ округлите до двух знаков после точки-разделителя.

In [ ]:
query_vac = f'''
    SELECT  
        round(AVG(length(key_skills)
        -length(replace(key_skills, CHR(9), ''))+1), 2) AS key_skills_in_vacancy
    FROM  vacancies
    WHERE 
        (name ILIKE '%data scientist%'
        or name ILIKE  '%data science%'
        or name ILIKE  '%исследователь данных%'
        or (name LIKE  '%ML%' and name NOT ILIKE '%HTML%')
        or name ILIKE  '%machine learning%'
        or name ILIKE  '%машинн%обучен%')
'''
vac_df = pd.read_sql_query(query_vac, connection)

C:\Users\Mephistophel\AppData\Local\Temp\ipykernel_8812\1542560165.py:16: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  vac_df = pd.read_sql_query(query_vac, connection)

In [45]:
vac_df

   key_skills_in_vacanc
0                  6.41

6. Напишите запрос, позволяющий вычислить, какую зарплату для DS в **среднем** указывают для каждого типа требуемого опыта (уникальное значение из поля *experience*). 

При решении задачи примите во внимание следующее:
1. Рассматриваем только вакансии, у которых заполнено хотя бы одно из двух полей с зарплатой.
2. Если заполнены оба поля с зарплатой, то считаем зарплату по каждой вакансии как сумму двух полей, делённую на 2. Если заполнено только одно из полей, то его и считаем зарплатой по вакансии.
3. Если в расчётах участвует null, в результате он тоже даст null (посмотрите, что возвращает запрос select 1 + null). Чтобы избежать этой ситуацию, мы воспользуемся функцией [coalesce](https://postgrespro.ru/docs/postgresql/9.5/functions-conditional#functions-coalesce-nvl-ifnull), которая заменит null на значение, которое мы передадим. Например, посмотрите, что возвращает запрос `select 1 + coalesce(null, 0)`

Выясните, на какую зарплату в среднем может рассчитывать дата-сайентист с опытом работы от 3 до 6 лет. Результат округлите до целого числа.

In [ ]:
query_vac = f'''
    SELECT  
        DISTINCT experience,
        ROUND(AVG(coalesce((salary_from+salary_to)/2, salary_from, salary_to)), 0) AS mean_salary      
    FROM  vacancies
    WHERE 
        (name ILIKE '%data scientist%'
        or name ILIKE  '%data science%'
        or name ILIKE  '%исследователь данных%'
        or (name LIKE  '%ML%' and name NOT ILIKE '%HTML%')
        or name ILIKE  '%machine learning%'
        or name ILIKE  '%машинн%обучен%')
        AND (experience ILIKE '%от 3 до 6 лет%')
    
    GROUP BY 1
'''
vac_df = pd.read_sql_query(query_vac, connection)

C:\Users\Mephistophel\AppData\Local\Temp\ipykernel_8812\2187274505.py:19: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  vac_df = pd.read_sql_query(query_vac, connection)

In [47]:
vac_df

      experience  mean_salary
0  От 3 до 6 лет     243115.0

***

**Выводы по юниту:**
данный юнит позволил нам всесторонне рассмотреть конкретную выброрку по вакансиям DataSientist в зависимости от опыта работы, размера зарплаты, сколько в целом вакансий такого типа и какие навыки указывают работодатели в объявлении.

# Общий вывод по проекту

Рынок труда в различных городах практически одинаковый, в особенности это касается городов-миллионников.

Лидером по количеству работодателей является Москва.

Чаще всего размещают вакансии в IT- сфере.

In [ ]:
# подведем итог исследования, обобщите выводы
# здесь можно (это будет плюсом) провести дополнительные исследования данных, сделать прогнозы, продумать варианты продолжения исследования

'''Найдем самые высокооплачиваемые вакансии IT-сферы.'''
query_vac = f'''
    SELECT  
        name AS vacancies_IT,
        round(AVG(coalesce((salary_from+salary_to)/2, salary_from, salary_to)), 0) AS mean_salary     
    FROM
        vacancies      
    WHERE 
        name LIKE  '%IT%'
    GROUP BY 1
    ORDER BY 2 DESC nulls last
    LIMIT 5
    
'''
vac_df = pd.read_sql_query(query_vac, connection)
vac_df

C:\Users\Mephistophel\AppData\Local\Temp\ipykernel_8812\470965687.py:20: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  vac_df = pd.read_sql_query(query_vac, connection)

                                  vacancies_it  mean_salary
0                 Директор IT (HoReCa, Retail)     550000.0
1  Директор по информационным технологиям (IT)     320000.0
2                                  IT Директор     300000.0
3              IT специалист (PHP-разработчик)     300000.0
4               Руководитель IT инфраструктуры     250000.0

In [55]:
fig = px.histogram(
    vac_df,
    y='mean_salary',
    x=vac_df['vacancies_it'],
    text_auto='.0f',
    title="Самые высокооплачиваемые вакансии в IT-сфере (по среднему уровню предлагаемой ЗП)"
)
fig.update_layout(
    yaxis_title="Средний предлагаемый уровень ЗП, руб.",
    xaxis_title="Должность",
    uniformtext_minsize = 6,
    title_x = 0.5,
    margin=dict(t=70)
)
fig.update_traces(
    textposition='auto',
    textfont_color='black'
)
fig.show()